### ISSUE TITLE
[Vue.js / html] add target blank to component link

### ISSUE THREAD

**Issue by T3kstiil3** [T3kstiil3/github-corners-web-components#9]
Add target attribute to component link and dont forget to build a new release 👷‍♂️
target attribute need to have default value _blank

![image](https://user-images.githubusercontent.com/3717296/46505223-6c749380-c7fe-11e8-8a52-b24daf97de53.png)

**Comment by viveksdf** [comment]
@T3stiil3 I will work on it

**Comment by viveksdf** [comment]
@T3kstiil3  Can't push permission denied

**Comment by viveksdf** [comment]
@T3kstiil3 Done.

**Comment by T3kstiil3** [comment]
Thx @viveksdf 🎉
